/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BO.ConsultaBO;
import Configuracion.DependencyInjector;
import DTO.CitaDTO;
import DTO.ConsultaDTO;
import DTO.MedicoDTO;
import Exception.NegocioException;
import Mapper.CitaMapper;
import Mapper.MedicoMapper;
import entidades.Cita;
import javax.swing.JOptionPane;

/**
 *  Clase que permite al médico registrar el diagnostico,
 * tratamiento y observaciones de un paciente.
 * @author norma
 */
public class AtenderConsulta extends javax.swing.JFrame {

    private MedicoDTO medico;
    private CitaDTO citaDTO;
    private ConsultaBO consultaBO = DependencyInjector.crearConsultaBO();

    /**
     * Constructor de la clase con los datos del médico y del paciente.
     * @param medicoDTO Datos del medico que atenderá la consulta
     * @param citaDTO Datos de la cita para el paciente
     */
    public AtenderConsulta(MedicoDTO medicoDTO, CitaDTO citaDTO) {
        this.medico = medicoDTO;
        this.citaDTO = citaDTO;
        initComponents();
        txtNombrePaciente.setText(citaDTO.getPaciente().getNombre());
        txtNombrePaciente.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTratamiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Consulta");

        jLabel2.setText("Paciente");

        jLabel3.setText("Diagnóstico");

        jLabel4.setText("Tratamiento");

        jLabel5.setText("Observaciones");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiagnostico)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTratamiento)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnRegistrar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que aparece al hacer click en el botón "Cancelar",
     * regresa a la ventana de la agenda
     * @param evt evento de acción cuando el usuario hace click en "Cancelar"
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new ConsultarAgenda(medico).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Método que procesa y registra la consulta. 
     * Cuando hace click en "Registrar".
     * @param evt evento de acción
     */
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        atenderConsultaCitaPrevia();
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables

    
    /**
     * Método que procesa los datos de la consulta, de una cita que
     * fue agendada.
     * Muestra mensajes de advertencia, para que no estén vacíos
     * los campos.
     */
    private void atenderConsultaCitaPrevia() {

        String diagnostico = txtDiagnostico.getText();
        String tratamiento = txtTratamiento.getText();
        String observaciones = txtObservaciones.getText();

        if (diagnostico.isEmpty() || tratamiento.isEmpty() || observaciones.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.");
            return;
        }

        ConsultaDTO consultaDTO = new ConsultaDTO();
        consultaDTO.setDiagnostico(diagnostico);
        consultaDTO.setTratamiento(tratamiento);
        consultaDTO.setObservaciones(observaciones);

        CitaMapper mapper_cita = new CitaMapper();
        Cita cita = mapper_cita.toEntity(citaDTO);
        consultaDTO.setCita(cita);

        try {
            boolean resultado = consultaBO.atenderCitaProgramada(consultaDTO, medico);
            if (resultado) {
                JOptionPane.showMessageDialog(this, "La consulta ha sido registrada correctamente.");
                new ConsultarAgenda(medico).setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar la consulta.");
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al atender la cita: " + e.getMessage());
        }
    }
}
