/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BO.PacienteBO;
import Configuracion.DependencyInjector;
import DTO.ConsultaDTO;
import DTO.MedicoDTO;
import Exception.NegocioException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Clase que representa la interfaz gráfica para permitir que un médico
 * obtenga el historial de consultas de un paciente introduciendo su nombre
 * completo.
 * @author norma
 */
public class HistorialConsultasPacientesPorMedico extends javax.swing.JFrame {

    private MedicoDTO medico;
    private PacienteBO pacienteBO = DependencyInjector.crearPacienteBO();

    /**
     * Constructor de la clase. Recibe un objeto MedicoDTO como parámetro.
     * @param medicoDTO Objeto que representa al médico que verá el
     * historial de consultas de su paciente.
     */
    public HistorialConsultasPacientesPorMedico(MedicoDTO medicoDTO) {
        this.medico = medicoDTO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsultas = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Historial Consultas Pacientes");

        jLabel2.setText("Nombre Completo Paciente");

        tablaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha y hora", "Tipo", "Diagnóstico", "Tratamiento"
            }
        ));
        jScrollPane1.setViewportView(tablaConsultas);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnBuscar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
                            .addComponent(btnCancelar))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método invocado cuando el usuario presiona "Cancelar".
     * Cierra la ventana actual y abre la ventana del perfil del médico.
     * @param evt Evento de acción generado por el botón
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new PerfilMedico(medico).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Método que se ejecuta cuando el usuario presiona el botón "Buscar"
     * Obtiene el nombre del paciente ingresado y busca su historial de consultas.
     * @param evt Evento de acción
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombrePaciente = txtNombre.getText().trim();
        String nombreCompletoMedico = String.format("%s %s %s",
                medico.getNombre(),
                medico.getApellido_paterno(),
                medico.getApellido_materno() != null ? medico.getApellido_materno() : ""
        ).trim();
        if (!nombrePaciente.isEmpty()) {

            cargarHistorialConsultas(nombrePaciente, nombreCompletoMedico);
        } else {
            DefaultTableModel tabla = (DefaultTableModel) tablaConsultas.getModel();
            tabla.setRowCount(0);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaConsultas;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que se encarga de cargar el historial de consultas de un paciente
     * con el médico actual.
     * Agrega las consultas obtenidas a una tabla.
     * @param nombrePaciente Nombre completo del paciente a buscar.
     * @param nombreMedico Nombre del médico que realizó las consulta.
     */
    private void cargarHistorialConsultas(String nombrePaciente, String nombreMedico) {
        try {

            List<ConsultaDTO> historial = pacienteBO.obtenerHistorialConsultasDelPacientePorMedico(nombrePaciente, nombreMedico);
            System.out.println(historial);
            DefaultTableModel tabla = (DefaultTableModel) tablaConsultas.getModel();
            tabla.setRowCount(0);

            for (ConsultaDTO consulta : historial) {
                Object[] row = new Object[]{
                    consulta.getCita().getFecha_hora(),
                    consulta.getCita().getTipo(),
                    consulta.getDiagnostico(),
                    consulta.getTratamiento()
                };
                tabla.addRow(row);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }
}
