/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.PacienteDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author norma
 */
public class PerfilPaciente extends javax.swing.JFrame {
    
    private PacienteDTO paciente;
    
    /**
     * Creates new form PerfilPaciente
     */
    public PerfilPaciente(PacienteDTO pacienteDTO) {
        this.paciente = pacienteDTO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAgendarCita = new javax.swing.JButton();
        btnVerCancelarCitasProgramadas = new javax.swing.JButton();
        btnGenerarCitaEmergencia = new javax.swing.JButton();
        btnHistorialConsultas = new javax.swing.JButton();
        btnActualizarDatos = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Perfil Paciente");

        btnAgendarCita.setText("Agendar Cita");
        btnAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarCitaActionPerformed(evt);
            }
        });

        btnVerCancelarCitasProgramadas.setText("Ver/Cancelar Citas programadas");
        btnVerCancelarCitasProgramadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCancelarCitasProgramadasActionPerformed(evt);
            }
        });

        btnGenerarCitaEmergencia.setText("Generar cita de emergencia");
        btnGenerarCitaEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCitaEmergenciaActionPerformed(evt);
            }
        });

        btnHistorialConsultas.setText("Historial de consultas");
        btnHistorialConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialConsultasActionPerformed(evt);
            }
        });

        btnActualizarDatos.setText("Actualizar datos");
        btnActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDatosActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGenerarCitaEmergencia)
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btnActualizarDatos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnHistorialConsultas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnVerCancelarCitasProgramadas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnCerrarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(btnAgendarCita)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(btnAgendarCita)
                .addGap(36, 36, 36)
                .addComponent(btnGenerarCitaEmergencia)
                .addGap(29, 29, 29)
                .addComponent(btnVerCancelarCitasProgramadas)
                .addGap(28, 28, 28)
                .addComponent(btnHistorialConsultas)
                .addGap(37, 37, 37)
                .addComponent(btnActualizarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCancelarCitasProgramadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCancelarCitasProgramadasActionPerformed
//        new VerCancelarCitasProgramadas().setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_btnVerCancelarCitasProgramadasActionPerformed

    private void btnActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDatosActionPerformed
//        new ActualizarDatos().setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_btnActualizarDatosActionPerformed

    private void btnAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarCitaActionPerformed
        new AgendarCita(paciente).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAgendarCitaActionPerformed

    private void btnGenerarCitaEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCitaEmergenciaActionPerformed
        new GenerarCitaEmergencia( paciente).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGenerarCitaEmergenciaActionPerformed

    private void btnHistorialConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialConsultasActionPerformed
//        new HistorialConsultas().setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_btnHistorialConsultasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que quiere cerrar sesión?",
                "Confirmar cierre de sesión", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDatos;
    private javax.swing.JButton btnAgendarCita;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGenerarCitaEmergencia;
    private javax.swing.JButton btnHistorialConsultas;
    private javax.swing.JButton btnVerCancelarCitasProgramadas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
